"è[
ŸDeviceConv2DBackpropFilter";gradient_tape/sequential/conv2d/Conv2D/Conv2DBackpropFilter(1;ßO[ã@9;ßO[ã@A;ßO[ã@I;ßO[ã@QìÁ¶UÆÍ?YìÁ¶UÆÍ?ŠUnknown
€DeviceReluGrad"(gradient_tape/sequential/conv2d/ReluGrad(1Ûù~jÕ@9Ûù~jÕ@AÛù~jÕ@IÛù~jÕ@QPyä”}À?YMõ!×?ŠUnknown
•DeviceMaxPoolGrad":gradient_tape/sequential/max_pooling2d/MaxPool/MaxPoolGrad(1V-²µéÓ@9V-²µéÓ@AV-²µéÓ@IV-²µéÓ@Q@eà&¿?Y"¥áf­ëŞ?ŠUnknown
gDevice_Recv"IteratorGetNext/_2(1+‡3Ì@9+‡3Ì@A+‡3Ì@I+‡3Ì@Q‹ÁI¼¶?YÂj‘<®7â?ŠUnknown
¡DeviceConv2DBackpropFilter"=gradient_tape/sequential/conv2d_1/Conv2D/Conv2DBackpropFilter(1Zd;/#Ì@9Zd;/#Ì@AZd;/#Ì@IZd;/#Ì@Qı˜9X¶?Y¢nÄCù÷ä?ŠUnknown
wDeviceMaxPool" sequential/max_pooling2d/MaxPool(1•C‹¼äÆ@9•C‹¼äÆ@A•C‹¼äÆ@I•C‹¼äÆ@Q Ä|Gè±?Y¥]35ç?ŠUnknown
tDevice_FusedConv2D"sequential/conv2d_1/Relu(1“Vy¿@9“Vy¿@A“Vy¿@I“Vy¿@QC;Hš>¨?YY†æ¾è?ŠUnknown
ŸDeviceConv2DBackpropInput"<gradient_tape/sequential/conv2d_1/Conv2D/Conv2DBackpropInput(1øSã¥[j¾@9øSã¥[j¾@AøSã¥[j¾@IøSã¥[j¾@Q¡Úw	Ê§?Y™-;ê?ŠUnknown
r	Device_FusedConv2D"sequential/conv2d/Relu(1ºI+aº@9ºI+aº@AºI+aº@IºI+aº@Q’JûBW¢¤?Y¬¸È¡³…ë?ŠUnknown

DeviceBiasAddGrad"3gradient_tape/sequential/conv2d/BiasAdd/BiasAddGrad(1ÇK7‰áûµ@9ÇK7‰áûµ@AÇK7‰áûµ@IÇK7‰áûµ@Q÷¸¤#2¡?Y‹:ÜÕ˜ì?ŠUnknown
DDeviceIDLE"IDLE1#Ûù~Ê·²@A#Ûù~Ê·²@Q229ÌKH?Yv:ƒí?ŠUnknown
‚DeviceReluGrad"*gradient_tape/sequential/conv2d_1/ReluGrad(1˜nƒ€a¡@9˜nƒ€a¡@A˜nƒ€a¡@I˜nƒ€a¡@QìUï_Ñ0‹?YuÁõÛïí?ŠUnknown
—DeviceMaxPoolGrad"<gradient_tape/sequential/max_pooling2d_1/MaxPool/MaxPoolGrad(1®Gá:3¡@9®Gá:3¡@A®Gá:3¡@I®Gá:3¡@Q;šßnèŠ?YŞ?8}[î?ŠUnknown
¡DeviceConv2DBackpropFilter"=gradient_tape/sequential/conv2d_2/Conv2D/Conv2DBackpropFilter(1®Gáz³@9®Gáz³@A®Gáz³@I®Gáz³@Q« ‚A³ˆ?YaHŒ»î?ŠUnknown
ŸDeviceConv2DBackpropInput"<gradient_tape/sequential/conv2d_2/Conv2D/Conv2DBackpropInput(1°rh‘mq@9°rh‘mq@A°rh‘mq@I°rh‘mq@Q
ÇÌÄ>¹y?Yïáœ‚şîî?ŠUnknown
yDeviceMaxPool""sequential/max_pooling2d_1/MaxPool(1î|?5^¹@9î|?5^¹@Aî|?5^¹@Iî|?5^¹@QRÒlJNx?Y”»1ï?ŠUnknown
DeviceBiasAddGrad"5gradient_tape/sequential/conv2d_1/BiasAdd/BiasAddGrad(1d;ßOB‹@9d;ßOB‹@Ad;ßOB‹@Id;ßOB‹@Q¿ñ ü¢Ru?Ywı)e´Iï?ŠUnknown
tDevice_FusedConv2D"sequential/conv2d_2/Relu(1B`åĞ"ÆŠ@9B`åĞ"ÆŠ@AB`åĞ"ÆŠ@IB`åĞ"ÆŠ@QÑ•]wQñt?Y£¸—sï?ŠUnknown
ºDevice	Transpose"agradient_tape/sequential/conv2d/Conv2D/Conv2DBackpropFilter-0-TransposeNHWCToNCHW-LayoutOptimizer(1×£p=
d†@9×£p=
d†@A×£p=
d†@I×£p=
d†@QÒ^Óœƒq?YGv¿A–ï?ŠUnknown
…DeviceResourceApplyAdam"$Adam/Adam/update_6/ResourceApplyAdam(1!°rh‘·~@9!°rh‘·~@A!°rh‘·~@I!°rh‘·~@QŸJ"Úåh?Y’˜™'¥®ï?ŠUnknown
—DeviceMaxPoolGrad"<gradient_tape/sequential/max_pooling2d_2/MaxPool/MaxPoolGrad(1ªñÒMbt@9ªñÒMbt@AªñÒMbt@IªñÒMbt@QëTÄGy_?Y”Â{Ëa¾ï?ŠUnknown
‚DeviceReluGrad"*gradient_tape/sequential/conv2d_2/ReluGrad(1+‡Ín@9+‡Ín@A+‡Ín@I+‡Ín@Qd£»X?Y©mÊï?ŠUnknown
mDeviceMatMul"sequential/dense/MatMul(1®Gáz´i@9®Gáz´i@A®Gáz´i@I®Gáz´i@Qzk”CT?YÕIÒJ{Ôï?ŠUnknown
}DeviceMatMul"'gradient_tape/sequential/dense/MatMul_1(1;ßO—ff@9;ßO—ff@A;ßO—ff@I;ßO—ff@Q‡iùØ›…Q?YŠÆ¾>İï?ŠUnknown
{DeviceMatMul"%gradient_tape/sequential/dense/MatMul(1sh‘í|c`@9sh‘í|c`@Ash‘í|c`@Ish‘í|c`@Q˜÷ˆùo£I?YÈ(½ô¦ãï?ŠUnknown
yDeviceMaxPool""sequential/max_pooling2d_2/MaxPool(1q=
×£_@9q=
×£_@Aq=
×£_@Iq=
×£_@QÃ2õ‘LH?Yyu:ºéï?ŠUnknown
DeviceBiasAddGrad"5gradient_tape/sequential/conv2d_2/BiasAdd/BiasAddGrad(1 /İ$¦]@9 /İ$¦]@A /İ$¦]@I /İ$¦]@Qô°l1G?YeyÕZ†ïï?ŠUnknown
£Device	Transpose"Jsequential/max_pooling2d_2/MaxPool-0-2-TransposeNCHWToNHWC-LayoutOptimizer(1V-RH@9V-RH@AV-RH@IV-RH@QHu»p 3?YÔãçñï?ŠUnknown
»Device	Transpose"bgradient_tape/sequential/max_pooling2d_2/MaxPool/MaxPoolGrad-2-TransposeNHWCToNCHW-LayoutOptimizer(1ƒÀÊ¡EG@9ƒÀÊ¡EG@AƒÀÊ¡EG@IƒÀÊ¡EG@QC	rÂ‚2?Yß;o'ôï?ŠUnknown
ÚDevice#SparseSoftmaxCrossEntropyWithLogits"gsparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits(1ƒÀÊ¡åD@9ƒÀÊ¡åD@AƒÀÊ¡åD@IƒÀÊ¡åD@Q‹Ø¤	~X0?Y°ı~2öï?ŠUnknown
\DeviceArgMax"ArgMax(1¢E¶óı$B@9¢E¶óı$B@A¢E¶óı$B@I¢E¶óı$B@Q&Ñ¦¤b,?YÁ€G©ø÷ï?ŠUnknown
q DeviceSoftmax"sequential/dense_1/Softmax(1Év¾Ÿ/-@9Év¾Ÿ/-@AÉv¾Ÿ/-@IÉv¾Ÿ/-@QÖÕßiéÓ?YÀÏ’H¯øï?ŠUnknown
}!DeviceMatMul"'gradient_tape/sequential/dense_1/MatMul(1®Gázî$@9®Gázî$@A®Gázî$@I®Gázî$@Qd~C²_?YÜa`A2ùï?ŠUnknown
o"DeviceMatMul"sequential/dense_1/MatMul(1F¶óıÔx!@9F¶óıÔx!@AF¶óıÔx!@IF¶óıÔx!@QÇFÅ¾PU?Yñ\£–Ÿùï?ŠUnknown
#DeviceMatMul")gradient_tape/sequential/dense_1/MatMul_1(1¦›Ä °r @9¦›Ä °r @A¦›Ä °r @I¦›Ä °r @Qkëb7»	?Yùä€ƒúï?ŠUnknown
…$DeviceResourceApplyAdam"$Adam/Adam/update_2/ResourceApplyAdam(1î|?5^º@9î|?5^º@Aî|?5^º@Iî|?5^º@Q¬+VŞ?YRZûWúï?ŠUnknown
ƒ%DeviceResourceApplyAdam""Adam/Adam/update/ResourceApplyAdam(1ÓMbX9@9ÓMbX9@AÓMbX9@IÓMbX9@QLLèt£ÿ>Yw*åI–úï?ŠUnknown
…&DeviceResourceApplyAdam"$Adam/Adam/update_4/ResourceApplyAdam(1×£p=
×@9×£p=
×@A×£p=
×@I×£p=
×@Q

Ie«	ÿ>Y	õ;]Ôúï?ŠUnknown
…'DeviceResourceApplyAdam"$Adam/Adam/update_8/ResourceApplyAdam(1¤p=
×£@9¤p=
×£@A¤p=
×£@I¤p=
×£@QŒf#ú>YÖ;tmûï?ŠUnknown
…(DeviceResourceApplyAdam"$Adam/Adam/update_9/ResourceApplyAdam(1P—nƒ@9P—nƒ@AP—nƒ@IP—nƒ@Q!!Î÷ØÔù>Yr+&<ûï?ŠUnknown
…)DeviceResourceApplyAdam"$Adam/Adam/update_7/ResourceApplyAdam(1ffffff@9ffffff@Affffff@Iffffff@QA©R­nõ>Y•Ï€ôfûï?ŠUnknown
*DeviceBiasAddGrad"2gradient_tape/sequential/dense/BiasAdd/BiasAddGrad(11¬Zd@91¬Zd@A1¬Zd@I1¬Zd@Qæå´8mõ>Yÿ@§Î‘ûï?ŠUnknown
+DeviceBiasAddGrad"4gradient_tape/sequential/dense_1/BiasAdd/BiasAddGrad(1áz®Gá
@9áz®Gá
@Aáz®Gá
@Iáz®Gá
@Q„áŒõ>YÁÛ»ûï?ŠUnknown
…,DeviceResourceApplyAdam"$Adam/Adam/update_3/ResourceApplyAdam(1B`åĞ"Û	@9B`åĞ"Û	@AB`åĞ"Û	@IB`åĞ"Û	@Qba"3€9ô>YLjÁNäûï?ŠUnknown
[-DevicePow"Adam/Pow(1R¸…ëQ@9R¸…ëQ@AR¸…ëQ@IR¸…ëQ@QİÜ-íó>YlÅ›Z
üï?ŠUnknown
….DeviceResourceApplyAdam"$Adam/Adam/update_1/ResourceApplyAdam(1+‡ÙÎ@9+‡ÙÎ@A+‡ÙÎ@I+‡ÙÎ@Q_ÖfŸò>Y*ri™/üï?ŠUnknown
¤/DeviceDivNoNan"Lgradient_tape/sparse_categorical_crossentropy/weighted_loss/value/div_no_nan(1²ï§ÆK@9²ï§ÆK@A²ï§ÆK@I²ï§ÆK@Q//.à8ò>Y†p*Tüï?ŠUnknown
…0DeviceResourceApplyAdam"$Adam/Adam/update_5/ResourceApplyAdam(1
×£p=
@9
×£p=
@A
×£p=
@I
×£p=
@QÃÃ•Sò>Y²exüï?ŠUnknown
X1DeviceSum"Sum_2(1bX9´È@9bX9´È@AbX9´È@IbX9´È@QXXı'ZÒñ>Y­g»›üï?ŠUnknown
€2DeviceAssignAddVariableOp"Adam/Adam/AssignAddVariableOp(1ºI+‡@9ºI+‡@AºI+‡@IºI+‡@QíìdüŸñ>Yw`Gù¾üï?ŠUnknown
]3DeviceAddV2"Adam/add(1ºI+‡@9ºI+‡@AºI+‡@IºI+‡@QíìdüŸñ>YAYu7âüï?ŠUnknown
Z4DeviceEqual"Equal(1ºI+‡@9ºI+‡@AºI+‡@IºI+‡@QíìdüŸñ>YR£uıï?ŠUnknown
–5DeviceTile"Bgradient_tape/sparse_categorical_crossentropy/weighted_loss/Tile_1(1Ãõ(\Â@9Ãõ(\Â@AÃõ(\Â@IÃõ(\Â@Q«ª›yMñ>YBE>€'ıï?ŠUnknown
x6DeviceAssignAddVariableOp"AssignAddVariableOp_4(1+‡ÙÎ÷@9+‡ÙÎ÷@A+‡ÙÎ÷@I+‡ÙÎ÷@Quuáî<ï>Y#Ö,½Fıï?ŠUnknown
¨7DeviceMul"Ugradient_tape/sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/mul(1+‡ÙÎ÷@9+‡ÙÎ÷@A+‡ÙÎ÷@I+‡ÙÎ÷@Quuáî<ï>Ygúeıï?ŠUnknown
V8DeviceMul"Mul(1ƒÀÊ¡E¶@9ƒÀÊ¡E¶@AƒÀÊ¡E¶@IƒÀÊ¡E¶@Q°9hÖî>Yµ ƒĞ„ıï?ŠUnknown
o9DeviceBiasAdd"sequential/dense/BiasAdd(1;ßO—n@9;ßO—n@A;ßO—n@I;ßO—n@Qll¼…ÈÕì>Yq&L¦¡ıï?ŠUnknown
x:DeviceAssignAddVariableOp"AssignAddVariableOp_2(1“V-@9“V-@A“V-@I“V-@Q••‹.Boì>YıT¾ıï?ŠUnknown
i;DeviceRelu"sequential/dense/Relu(1D‹lçû©@9D‹lçû©@AD‹lçû©@ID‹lçû©@Qèç)€5¢ë>Y'ÕÃ·Ùıï?ŠUnknown
_<DeviceCast"Adam/Cast_1(1ôıÔxé&@9ôıÔxé&@AôıÔxé&@IôıÔxé&@Q::ÈÑ(Õê>Yï¦ìŒôıï?ŠUnknown
]=DevicePow"
Adam/Pow_1(1ôıÔxé&@9ôıÔxé&@AôıÔxé&@IôıÔxé&@Q::ÈÑ(Õê>Y·xbşï?ŠUnknown
X>DeviceCast"Cast(1ôıÔxé&@9ôıÔxé&@AôıÔxé&@IôıÔxé&@Q::ÈÑ(Õê>YJ>7*şï?ŠUnknown
q?DeviceBiasAdd"sequential/dense_1/BiasAdd(1L7‰A`å @9L7‰A`å @AL7‰A`å @IL7‰A`å @Qdc—z¢nê>YÅà¥Dşï?ŠUnknown
g@Device
LogicalAnd"
LogicalAnd(1¤p=
×£ @9¤p=
×£ @A¤p=
×£ @I¤p=
×£ @QŒf#ê>Y}èü­^şï?ŠUnknown
ADeviceReluGrad"'gradient_tape/sequential/dense/ReluGrad(1¤p=
×£ @9¤p=
×£ @A¤p=
×£ @I¤p=
×£ @QŒf#ê>Yä¶xşï?ŠUnknown
bBDeviceDivNoNan"
div_no_nan(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q¶µ5Ì•¡é>YØ®W’şï?ŠUnknown
dCDeviceDivNoNan"div_no_nan_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q¶µ5Ì•¡é>YP¤Dù«şï?ŠUnknown
¶DDeviceCast"bsparse_categorical_crossentropy/ArithmeticOptimizer/ReorderCastLikeAndValuePreserving_int64_Cast_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q¶µ5Ì•¡é>Y†pÚšÅşï?ŠUnknown
‹EDeviceDivNoNan"3sparse_categorical_crossentropy/weighted_loss/value(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q¶µ5Ì•¡é>Y¼<p<ßşï?ŠUnknown
fFDevice_Recv"strided_slice/_10(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q¶µ5Ì•¡é>YòŞøşï?ŠUnknown
xGDeviceAssignAddVariableOp"AssignAddVariableOp_3(1Tã¥›Ä  @9Tã¥›Ä  @ATã¥›Ä  @ITã¥›Ä  @QßŞu;é>Y÷}ÿï?ŠUnknown
vHDeviceAssignAddVariableOp"AssignAddVariableOp(1X9´Èv¾ÿ?9X9´Èv¾ÿ?AX9´Èv¾ÿ?IX9´Èv¾ÿ?QÔ‰Ôè>YË›í*ÿï?ŠUnknown
ZIDeviceCast"Cast_4(1X9´Èv¾ÿ?9X9´Èv¾ÿ?AX9´Èv¾ÿ?IX9´Èv¾ÿ?QÔ‰Ôè>YŸ¹'ÂCÿï?ŠUnknown
ZJDeviceCast"Cast_2(1¬Zd;ÿ?9¬Zd;ÿ?A¬Zd;ÿ?I¬Zd;ÿ?Q11£Ænè>YB€*0\ÿï?ŠUnknown
ZKDeviceCast"Cast_3(1¬Zd;ÿ?9¬Zd;ÿ?A¬Zd;ÿ?I¬Zd;ÿ?Q11£Ænè>YåF-tÿï?ŠUnknown
´LDeviceCast"`sparse_categorical_crossentropy/ArithmeticOptimizer/ReorderCastLikeAndValuePreserving_int64_Cast(1¬Zd;ÿ?9¬Zd;ÿ?A¬Zd;ÿ?I¬Zd;ÿ?Q11£Ænè>Yˆ0ÿï?ŠUnknown
„MDeviceSum"1sparse_categorical_crossentropy/weighted_loss/Sum(1¬Zd;ÿ?9¬Zd;ÿ?A¬Zd;ÿ?I¬Zd;ÿ?Q11£Ænè>Y+Ô2z¥ÿï?ŠUnknown
xNDeviceAssignAddVariableOp"AssignAddVariableOp_1(1¸…ëQ¸ş?9¸…ëQ¸ş?A¸…ëQ¸ş?I¸…ëQ¸ş?QZZro|è>YC¯½ÿï?ŠUnknown
“ODeviceCast"?sparse_categorical_crossentropy/weighted_loss/num_elements/Cast(1ÙÎ÷Sã¥û?9ÙÎ÷Sã¥û?AÙÎ÷Sã¥û?IÙÎ÷Sã¥û?QQQMdV å>Yê§"Óÿï?ŠUnknown
]PDevice_Recv"Size/_12(1%•C‹ö?9%•C‹ö?A%•C‹ö?I%•C‹ö?Q¤s/K¢á>Y×PÄäÿï?ŠUnknown
“QDevice_Recv">sparse_categorical_crossentropy/weighted_loss/num_elements/_14(1j¼t“ö?9j¼t“ö?Aj¼t“ö?Ij¼t“ö?Q4¥8á>Y<|áüõÿï?ŠUnknown
gRDevice_Recv"IteratorGetNext/_4(1š™™™™™é?9š™™™™™é?Aš™™™™™é?Iš™™™™™é?Qöõ‰=Ô>Y      ğ?ŠUnknown
BSHostIDLE"IDLE1şÔxé&Ñ•@AşÔxé&Ñ•@a…Æ¸Kë?i…Æ¸Kë?ŠUnknown
uTHostFlushSummaryWriter"FlushSummaryWriter(1ğ§ÆK7S@9ğ§ÆK7S@Ağ§ÆK7S@Iğ§ÆK7S@aÂJ>9~¦§?i1ƒZœ³~ì?ŠUnknown
eUHost
LogicalAnd"
LogicalAnd(1L7‰A`O@9L7‰A`O@AL7‰A`O@IL7‰A`O@aû®:ô>£?i!.İ¢²í?ŠUnknown
iVHostWriteSummary"WriteSummary(1`åĞ"ÛéF@9`åĞ"ÛéF@A`åĞ"ÛéF@I`åĞ"ÛéF@a6FÖæ_œ?iÑ_À¢•î?ŠUnknown
cWHostDataset"Iterator::Root(1Å °rhq<@9Å °rhq<@A‰A`åĞ¢.@I‰A`åĞ¢.@a«_xzø‚?iPAª)‚áî?ŠUnknown
eXHost_Send"IteratorGetNext/_6(1“V-.@9“V-.@A“V-.@I“V-.@a;^À°¯‚?iÉBm˜>,ï?ŠUnknown
mYHostDataset"Iterator::Root::Prefetch(1     @*@9     @*@A     @*@I     @*@a”0y?Ï@€?i‹'kÕAmï?ŠUnknown
eZHost_Send"IteratorGetNext/_3(1yé&1l&@9yé&1l&@Ayé&1l&@Iyé&1l&@a„_ÜÄ{?iJP#Ê¤ï?ŠUnknown
l[HostIteratorGetNext"IteratorGetNext(1bX9´#@9bX9´#@AbX9´#@IbX9´#@a#ú¯’w?idEƒîÓï?ŠUnknown
e\Host_Send"IteratorGetNext/_1(1'1¬Ú@9'1¬Ú@A'1¬Ú@I'1¬Ú@aÏú_; p?iZ®.õï?ŠUnknown
a]HostIdentity"Identity(1F¶óıÔx@9F¶óıÔx@AF¶óıÔx@IF¶óıÔx@a»Kõ£Ş¢U?i      ğ?ŠUnknown*ŞZ
ŸDeviceConv2DBackpropFilter";gradient_tape/sequential/conv2d/Conv2D/Conv2DBackpropFilter(1;ßO[ã@9;ßO[ã@A;ßO[ã@I;ßO[ã@Qª¦m¸¦Î?Yª¦m¸¦Î?ŠUnknown
€DeviceReluGrad"(gradient_tape/sequential/conv2d/ReluGrad(1Ûù~jÕ@9Ûù~jÕ@AÛù~jÕ@IÛù~jÕ@Qíş”,ÛùÀ?YxÔÍIĞ×?ŠUnknown
•DeviceMaxPoolGrad":gradient_tape/sequential/max_pooling2d/MaxPool/MaxPoolGrad(1V-²µéÓ@9V-²µéÓ@AV-²µéÓ@IV-²µéÓ@Q%HóÑÀ?Y
ÛÁÆ²Ôß?ŠUnknown
gDevice_Recv"IteratorGetNext/_2(1+‡3Ì@9+‡3Ì@A+‡3Ì@I+‡3Ì@Q£å­ö´¶?Y9j9øÀâ?ŠUnknown
¡DeviceConv2DBackpropFilter"=gradient_tape/sequential/conv2d_1/Conv2D/Conv2DBackpropFilter(1Zd;/#Ì@9Zd;/#Ì@AZd;/#Ì@IZd;/#Ì@Q™¹¤<5¨¶?Yl—àş•å?ŠUnknown
wDeviceMaxPool" sequential/max_pooling2d/MaxPool(1•C‹¼äÆ@9•C‹¼äÆ@A•C‹¼äÆ@I•C‹¼äÆ@QĞ,²;o²?YG­Cæãç?ŠUnknown
tDevice_FusedConv2D"sequential/conv2d_1/Relu(1“Vy¿@9“Vy¿@A“Vy¿@I“Vy¿@Qv=uúÄW©?YİšT“byé?ŠUnknown
ŸDeviceConv2DBackpropInput"<gradient_tape/sequential/conv2d_1/Conv2D/Conv2DBackpropInput(1øSã¥[j¾@9øSã¥[j¾@AøSã¥[j¾@IøSã¥[j¾@Qµ;Ñ¶Ë}¨?Y˜®ÁN?ë?ŠUnknown
r	Device_FusedConv2D"sequential/conv2d/Relu(1ºI+aº@9ºI+aº@AºI+aº@IºI+aº@QÃWJ‰×=¥?YTVÇUì?ŠUnknown

DeviceBiasAddGrad"3gradient_tape/sequential/conv2d/BiasAdd/BiasAddGrad(1ÇK7‰áûµ@9ÇK7‰áûµ@AÇK7‰áûµ@IÇK7‰áûµ@QƒwS º³¡?YŒ‹[qXpí?ŠUnknown
‚DeviceReluGrad"*gradient_tape/sequential/conv2d_1/ReluGrad(1˜nƒ€a¡@9˜nƒ€a¡@A˜nƒ€a¡@I˜nƒ€a¡@Q½¸ıÓºı‹?Yo‚«\Oàí?ŠUnknown
—DeviceMaxPoolGrad"<gradient_tape/sequential/max_pooling2d_1/MaxPool/MaxPoolGrad(1®Gá:3¡@9®Gá:3¡@A®Gá:3¡@I®Gá:3¡@Q¼'¸ó5³‹?Ycz4Oî?ŠUnknown
¡DeviceConv2DBackpropFilter"=gradient_tape/sequential/conv2d_2/Conv2D/Conv2DBackpropFilter(1®Gáz³@9®Gáz³@A®Gáz³@I®Gáz³@Q5‰'ø¬¸ˆ?Y3[èş±î?ŠUnknown
ŸDeviceConv2DBackpropInput"<gradient_tape/sequential/conv2d_2/Conv2D/Conv2DBackpropInput(1°rh‘mq@9°rh‘mq@A°rh‘mq@I°rh‘mq@Q®®óİ{z?Yèõæî?ŠUnknown
yDeviceMaxPool""sequential/max_pooling2d_1/MaxPool(1î|?5^¹@9î|?5^¹@Aî|?5^¹@Iî|?5^¹@QH½f¶j½x?Y¶ƒñoï?ŠUnknown
DeviceBiasAddGrad"5gradient_tape/sequential/conv2d_1/BiasAdd/BiasAddGrad(1d;ßOB‹@9d;ßOB‹@Ad;ßOB‹@Id;ßOB‹@QÖ×Sóu?Yb3™VDï?ŠUnknown
tDevice_FusedConv2D"sequential/conv2d_2/Relu(1B`åĞ"ÆŠ@9B`åĞ"ÆŠ@AB`åĞ"ÆŠ@IB`åĞ"ÆŠ@QL4/ì$u?Y€Àãtoï?ŠUnknown
ºDevice	Transpose"agradient_tape/sequential/conv2d/Conv2D/Conv2DBackpropFilter-0-TransposeNHWCToNCHW-LayoutOptimizer(1×£p=
d†@9×£p=
d†@A×£p=
d†@I×£p=
d†@Q9¶ãÌ™r?Yì‡¥„“ï?ŠUnknown
…DeviceResourceApplyAdam"$Adam/Adam/update_6/ResourceApplyAdam(1!°rh‘·~@9!°rh‘·~@A!°rh‘·~@I!°rh‘·~@QRŒÎ©÷»h?YxVO@¬ï?ŠUnknown
—DeviceMaxPoolGrad"<gradient_tape/sequential/max_pooling2d_2/MaxPool/MaxPoolGrad(1ªñÒMbt@9ªñÒMbt@AªñÒMbt@IªñÒMbt@QòÀ`#<3`?Y9·rJs¼ï?ŠUnknown
‚DeviceReluGrad"*gradient_tape/sequential/conv2d_2/ReluGrad(1+‡Ín@9+‡Ín@A+‡Ín@I+‡Ín@Q;¹9ÃKÍX?YTTğÙÈï?ŠUnknown
mDeviceMatMul"sequential/dense/MatMul(1®Gáz´i@9®Gáz´i@A®Gáz´i@I®Gáz´i@Qò¿æÉ²T?Yv£GU3Óï?ŠUnknown
}DeviceMatMul"'gradient_tape/sequential/dense/MatMul_1(1;ßO—ff@9;ßO—ff@A;ßO—ff@I;ßO—ff@Q ›İ§	R?YFq6)8Üï?ŠUnknown
{DeviceMatMul"%gradient_tape/sequential/dense/MatMul(1sh‘í|c`@9sh‘í|c`@Ash‘í|c`@Ish‘í|c`@Qp*º¦dJ?YæûäRÑâï?ŠUnknown
yDeviceMaxPool""sequential/max_pooling2d_2/MaxPool(1q=
×£_@9q=
×£_@Aq=
×£_@Iq=
×£_@QÉR¢Ó°I?Y{ä?éï?ŠUnknown
DeviceBiasAddGrad"5gradient_tape/sequential/conv2d_2/BiasAdd/BiasAddGrad(1 /İ$¦]@9 /İ$¦]@A /İ$¦]@I /İ$¦]@Q_Š7wÌßG?Y^²72
ïï?ŠUnknown
£Device	Transpose"Jsequential/max_pooling2d_2/MaxPool-0-2-TransposeNCHWToNHWC-LayoutOptimizer(1V-RH@9V-RH@AV-RH@IV-RH@Q¬ĞÙ9~•3?Y˜íşá|ñï?ŠUnknown
»Device	Transpose"bgradient_tape/sequential/max_pooling2d_2/MaxPool/MaxPoolGrad-2-TransposeNHWCToNCHW-LayoutOptimizer(1ƒÀÊ¡EG@9ƒÀÊ¡EG@AƒÀÊ¡EG@IƒÀÊ¡EG@Q#_^<Š2?Yd™€)Îóï?ŠUnknown
ÚDevice#SparseSoftmaxCrossEntropyWithLogits"gsparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits(1ƒÀÊ¡åD@9ƒÀÊ¡åD@AƒÀÊ¡åD@IƒÀÊ¡åD@QÃˆÏ¬Ó0?YfŠŸèõï?ŠUnknown
\DeviceArgMax"ArgMax(1¢E¶óı$B@9¢E¶óı$B@A¢E¶óı$B@I¢E¶óı$B@QÈ
%Ö8-?Y·ì(¼÷ï?ŠUnknown
qDeviceSoftmax"sequential/dense_1/Softmax(1Év¾Ÿ/-@9Év¾Ÿ/-@AÉv¾Ÿ/-@IÉv¾Ÿ/-@QÕ¾ñ?Ycã•'xøï?ŠUnknown
} DeviceMatMul"'gradient_tape/sequential/dense_1/MatMul(1®Gázî$@9®Gázî$@A®Gázî$@I®Gázî$@Q°«DzÚ?Y¼hûşøï?ŠUnknown
o!DeviceMatMul"sequential/dense_1/MatMul(1F¶óıÔx!@9F¶óıÔx!@AF¶óıÔx!@IF¶óıÔx!@Q%<r?M#?Y…ˆoùï?ŠUnknown
"DeviceMatMul")gradient_tape/sequential/dense_1/MatMul_1(1¦›Ä °r @9¦›Ä °r @A¦›Ä °r @I¦›Ä °r @Q:óûU!}
?Yu^"}Ùùï?ŠUnknown
…#DeviceResourceApplyAdam"$Adam/Adam/update_2/ResourceApplyAdam(1î|?5^º@9î|?5^º@Aî|?5^º@Iî|?5^º@Qôİ¤‡·?Yíñ@[,úï?ŠUnknown
ƒ$DeviceResourceApplyAdam""Adam/Adam/update/ResourceApplyAdam(1ÓMbX9@9ÓMbX9@AÓMbX9@IÓMbX9@Qp¡ñH ?Y­wmúï?ŠUnknown
…%DeviceResourceApplyAdam"$Adam/Adam/update_4/ResourceApplyAdam(1×£p=
×@9×£p=
×@A×£p=
×@I×£p=
×@QÃÄSË’óÿ>YU-f­úï?ŠUnknown
…&DeviceResourceApplyAdam"$Adam/Adam/update_8/ResourceApplyAdam(1¤p=
×£@9¤p=
×£@A¤p=
×£@I¤p=
×£@Qæ Â‘IÌú>YÙ1Àşâúï?ŠUnknown
…'DeviceResourceApplyAdam"$Adam/Adam/update_9/ResourceApplyAdam(1P—nƒ@9P—nƒ@AP—nƒ@IP—nƒ@QÈW“„—ú>Y [È-ûï?ŠUnknown
…(DeviceResourceApplyAdam"$Adam/Adam/update_7/ResourceApplyAdam(1ffffff@9ffffff@Affffff@Iffffff@Q‹…w~1ö>YïW+NDûï?ŠUnknown
)DeviceBiasAddGrad"2gradient_tape/sequential/dense/BiasAdd/BiasAddGrad(11¬Zd@91¬Zd@A1¬Zd@I1¬Zd@QCR‹ö>YıAkpûï?ŠUnknown
*DeviceBiasAddGrad"4gradient_tape/sequential/dense_1/BiasAdd/BiasAddGrad(1áz®Gá
@9áz®Gá
@Aáz®Gá
@Iáz®Gá
@Q}0X ¥õ>Yl­Bµ›ûï?ŠUnknown
…+DeviceResourceApplyAdam"$Adam/Adam/update_3/ResourceApplyAdam(1B`åĞ"Û	@9B`åĞ"Û	@AB`åĞ"Û	@IB`åĞ"Û	@Q“XucêÑô>YWtYÅûï?ŠUnknown
[,DevicePow"Adam/Pow(1R¸…ëQ@9R¸…ëQ@AR¸…ëQ@IR¸…ëQ@Qã¡\tI•ó>Y]ªƒìûï?ŠUnknown
…-DeviceResourceApplyAdam"$Adam/Adam/update_1/ResourceApplyAdam(1+‡ÙÎ@9+‡ÙÎ@A+‡ÙÎ@I+‡ÙÎ@Q¨ÿy¾+ó>YQ'Ûüï?ŠUnknown
¤.DeviceDivNoNan"Lgradient_tape/sparse_categorical_crossentropy/weighted_loss/value/div_no_nan(1²ï§ÆK@9²ï§ÆK@A²ï§ÆK@I²ï§ÆK@Qm}¡3Âò>YQP_8üï?ŠUnknown
…/DeviceResourceApplyAdam"$Adam/Adam/update_5/ResourceApplyAdam(1
×£p=
@9
×£p=
@A
×£p=
@I
×£p=
@QP´rnò>Y6Ujz]üï?ŠUnknown
X0DeviceSum"Sum_2(1bX9´È@9bX9´È@AbX9´È@IbX9´È@Q2ëC…¨Xò>Y¾_»+‚üï?ŠUnknown
€1DeviceAssignAddVariableOp"Adam/Adam/AssignAddVariableOp(1ºI+‡@9ºI+‡@AºI+‡@IºI+‡@Q"ã#ò>Yèos¦üï?ŠUnknown
]2DeviceAddV2"Adam/add(1ºI+‡@9ºI+‡@AºI+‡@IºI+‡@Q"ã#ò>Y€G»Êüï?ŠUnknown
Z3DeviceEqual"Equal(1ºI+‡@9ºI+‡@AºI+‡@IºI+‡@Q"ã#ò>Y<ïüï?ŠUnknown
–4DeviceTile"Bgradient_tape/sparse_categorical_crossentropy/weighted_loss/Tile_1(1Ãõ(\Â@9Ãõ(\Â@AÃõ(\Â@IÃõ(\Â@Q¾Æˆ’…ñ>YN±2ıï?ŠUnknown
x5DeviceAssignAddVariableOp"AssignAddVariableOp_4(1+‡ÙÎ÷@9+‡ÙÎ÷@A+‡ÙÎ÷@I+‡ÙÎ÷@QğFA$,ğ>YÑùŠ62ıï?ŠUnknown
¨6DeviceMul"Ugradient_tape/sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/mul(1+‡ÙÎ÷@9+‡ÙÎ÷@A+‡ÙÎ÷@I+‡ÙÎ÷@QğFA$,ğ>YTBã^Rıï?ŠUnknown
V7DeviceMul"Mul(1ƒÀÊ¡E¶@9ƒÀÊ¡E¶@AƒÀÊ¡E¶@IƒÀÊ¡E¶@Q¥û$NÍ¾ï>Yy°rıï?ŠUnknown
o8DeviceBiasAdd"sequential/dense/BiasAdd(1;ßO—n@9;ßO—n@A;ßO—n@I;ßO—n@Q Qj¯í>YÊúÆÌıï?ŠUnknown
x9DeviceAssignAddVariableOp"AssignAddVariableOp_2(1“V-@9“V-@A“V-@I“V-@QEóo‹Eí>Y¾jR­ıï?ŠUnknown
i:DeviceRelu"sequential/dense/Relu(1D‹lçû©@9D‹lçû©@AD‹lçû©@ID‹lçû©@QÑi8{urì>YöåÇ„Éıï?ŠUnknown
_;DeviceCast"Adam/Cast_1(1ôıÔxé&@9ôıÔxé&@AôıÔxé&@IôıÔxé&@Q[E}†_Ÿë>Ysl'$åıï?ŠUnknown
]<DevicePow"
Adam/Pow_1(1ôıÔxé&@9ôıÔxé&@AôıÔxé&@IôıÔxé&@Q[E}†_Ÿë>Yğò†Ã şï?ŠUnknown
X=DeviceCast"Cast(1ôıÔxé&@9ôıÔxé&@AôıÔxé&@IôıÔxé&@Q[E}†_Ÿë>Ymyæbşï?ŠUnknown
q>DeviceBiasAdd"sequential/dense_1/BiasAdd(1L7‰A`å @9L7‰A`å @AL7‰A`å @IL7‰A`å @Q ³ŒÔ5ë>Y»˜7şï?ŠUnknown
g?Device
LogicalAnd"
LogicalAnd(1¤p=
×£ @9¤p=
×£ @A¤p=
×£ @I¤p=
×£ @Qæ Â‘IÌê>YO—eRşï?ŠUnknown
@DeviceReluGrad"'gradient_tape/sequential/dense/ReluGrad(1¤p=
×£ @9¤p=
×£ @A¤p=
×£ @I¤p=
×£ @Qæ Â‘IÌê>Y)N1mşï?ŠUnknown
bADeviceDivNoNan"
div_no_nan(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q«d—¾bê>YvÀ”‡şï?ŠUnknown
dBDeviceDivNoNan"div_no_nan_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q«d—¾bê>YÛWËö¡şï?ŠUnknown
¶CDeviceCast"bsparse_categorical_crossentropy/ArithmeticOptimizer/ReorderCastLikeAndValuePreserving_int64_Cast_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q«d—¾bê>Y@ï‰Y¼şï?ŠUnknown
‹DDeviceDivNoNan"3sparse_categorical_crossentropy/weighted_loss/value(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q«d—¾bê>Y¥†H¼Öşï?ŠUnknown
fEDevice_Recv"strided_slice/_10(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q«d—¾bê>Y
ñşï?ŠUnknown
xFDeviceAssignAddVariableOp"AssignAddVariableOp_3(1Tã¥›Ä  @9Tã¥›Ä  @ATã¥›Ä  @ITã¥›Ä  @Qpü3ùé>Y»:ÿï?ŠUnknown
vGDeviceAssignAddVariableOp"AssignAddVariableOp(1X9´Èv¾ÿ?9X9´Èv¾ÿ?AX9´Èv¾ÿ?IX9´Èv¾ÿ?Q5j©¢¨é>Yº]ã§$ÿï?ŠUnknown
ZHDeviceCast"Cast_4(1X9´Èv¾ÿ?9X9´Èv¾ÿ?AX9´Èv¾ÿ?IX9´Èv¾ÿ?Q5j©¢¨é>Yc Œ7>ÿï?ŠUnknown
ZIDeviceCast"Cast_2(1¬Zd;ÿ?9¬Zd;ÿ?A¬Zd;ÿ?I¬Zd;ÿ?Qû×K¨&é>Y¯¨©]Wÿï?ŠUnknown
ZJDeviceCast"Cast_3(1¬Zd;ÿ?9¬Zd;ÿ?A¬Zd;ÿ?I¬Zd;ÿ?Qû×K¨&é>YûPÇƒpÿï?ŠUnknown
´KDeviceCast"`sparse_categorical_crossentropy/ArithmeticOptimizer/ReorderCastLikeAndValuePreserving_int64_Cast(1¬Zd;ÿ?9¬Zd;ÿ?A¬Zd;ÿ?I¬Zd;ÿ?Qû×K¨&é>YGùä©‰ÿï?ŠUnknown
„LDeviceSum"1sparse_categorical_crossentropy/weighted_loss/Sum(1¬Zd;ÿ?9¬Zd;ÿ?A¬Zd;ÿ?I¬Zd;ÿ?Qû×K¨&é>Y“¡Ğ¢ÿï?ŠUnknown
xMDeviceAssignAddVariableOp"AssignAddVariableOp_1(1¸…ëQ¸ş?9¸…ëQ¸ş?A¸…ëQ¸ş?I¸…ëQ¸ş?QÀEî­’¼è>YO•Œ»ÿï?ŠUnknown
“NDeviceCast"?sparse_categorical_crossentropy/weighted_loss/num_elements/Cast(1ÙÎ÷Sã¥û?9ÙÎ÷Sã¥û?AÙÎ÷Sã¥û?IÙÎ÷Sã¥û?Q`Ø¼ÏPCæ>Y>æÏÑÿï?ŠUnknown
]ODevice_Recv"Size/_12(1%•C‹ö?9%•C‹ö?A%•C‹ö?I%•C‹ö?Q§è_/'â>Y&÷ãÿï?ŠUnknown
“PDevice_Recv">sparse_categorical_crossentropy/weighted_loss/num_elements/_14(1j¼t“ö?9j¼t“ö?Aj¼t“ö?Ij¼t“ö?QÚ·Xºá>YŞŒm±õÿï?ŠUnknown
gQDevice_Recv"IteratorGetNext/_4(1š™™™™™é?9š™™™™™é?Aš™™™™™é?Iš™™™™™é?QvFæ$Ô>Y     ğ?ŠUnknown
uRHostFlushSummaryWriter"FlushSummaryWriter(1ğ§ÆK7S@9ğ§ÆK7S@Ağ§ÆK7S@Iğ§ÆK7S@avgšçûÒ?ivgšçûÒ?ŠUnknown
eSHost
LogicalAnd"
LogicalAnd(1L7‰A`O@9L7‰A`O@AL7‰A`O@IL7‰A`O@a\îj¹«åÎ?iRŠ»^7á?ŠUnknown
iTHostWriteSummary"WriteSummary(1`åĞ"ÛéF@9`åĞ"ÛéF@A`åĞ"ÛéF@I`åĞ"ÛéF@a"Ú°ÆÆ?iÚ ÕŞ
éæ?ŠUnknown
cUHostDataset"Iterator::Root(1Å °rhq<@9Å °rhq<@A‰A`åĞ¢.@I‰A`åĞ¢.@ab0</Ìs®?iàÃÈ¡GĞè?ŠUnknown
eVHost_Send"IteratorGetNext/_6(1“V-.@9“V-.@A“V-.@I“V-.@a£M[¾ş­?iº˜z‡3°ê?ŠUnknown
mWHostDataset"Iterator::Root::Prefetch(1     @*@9     @*@A     @*@I     @*@a|¡í…¶ª?iÒrÙï®Qì?ŠUnknown
eXHost_Send"IteratorGetNext/_3(1yé&1l&@9yé&1l&@Ayé&1l&@Iyé&1l&@aäöù¶I¦?i@IÛH¶í?ŠUnknown
lYHostIteratorGetNext"IteratorGetNext(1bX9´#@9bX9´#@AbX9´#@IbX9´#@aÁqß}ë¢?iP.@¹ åî?ŠUnknown
eZHost_Send"IteratorGetNext/_1(1'1¬Ú@9'1¬Ú@A'1¬Ú@I'1¬Ú@a«9¬æ°š?i¨û¡î‡ºï?ŠUnknown
a[HostIdentity"Identity(1F¶óıÔx@9F¶óıÔx@AF¶óıÔx@IF¶óıÔx@aáW^?i      ğ?ŠUnknown2Nvidia GPU (Pascal)